%[
//◆時間関連
//￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣
    times : %[
        // 時間定義。
        (時間定義名) : %[
            prefix : (文字列),
                // 背景画像定義のTIMEと置換される文字列。
            lightColor : (0xAARRGGBB or 0xRRGGBB), 
            lightType : (ltXXX),
                // 背景画像の環境光補正。
            brightness : (-255~255),
                // 背景画像の明度補正。
            contrast : (-100~100),
                // 背景画像のコントラスト補正。
            charLightColor : (0xAARRGGBB or 0xRRGGBB),
            charLightType : (ltXXX),
                // キャラクタ画像の環境光補正。
            charBrightness : (-255~255),
                // キャラクタ画像の明度補正。
            charContrast : (-100~100),
                // キャラクタ画像のコントラスト補正。
            trans : (トランジション),
                // この時間に変更されるときのトランジション。
        ] ... ,
    ]
    defaultTime : (文字列),
        // デフォルトの時間。
    timeTrans : (トランジション),
        // 時間が変更されるときのトランジション。

//◆舞台関連
//￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣
    stages : %[
        // 舞台定義。
        (舞台定義名) : %[
            image : (文字列),
                // 背景画像名。TIMEが置換される。
            cox : (座標値),
            coy : (座標値),
                // カメラ注視点。
            xoff : (座標値),
            yoff : (座標値),
                // デフォルトの x/ypos。
            blurx : (数値),
            blury : (数値),
                // ぼかし強度。
            resolution : (数値),
            resolutionx : (数値),
            resolutiony : (数値),
                // 解像度。
            trans : (トランジション),
                // この舞台に変更されるときのトランジション。
            dispTrans : (トランジション),
                // この舞台を表示/消去するときのトランジション。
            layers : %[
                // ステージレイヤの登録。
                (ステージレイヤ定義名) : %[
                    name : (文字列),
                        // ステージレイヤ定義名差し替え。
                    condition : (配列 or コンマ区切り文字列),
                        // 登録条件。列挙された時間の場合のみ表示。省略時は常に登録。
                    (コマンド名) : (属性値) ... ,
                        // 環境レイヤで実行するその他のコマンド。登録時に実行される。
                ] ... ,
            ], 
        ] ... ,
    ],
    bglevelz : (数値)
        // 舞台のカメラ用Z位置。
    stageDispTrans : (トランジション)
        // 舞台を表示/消去するときのトランジション。
    stageTrans : (トランジション)
        // 舞台 or 時間のトランジション。

//◆イベント絵関連
//￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣
    events : %[
        // イベント絵定義。event_[定義名].tjsでenvinit.tjs外に記述可。
        (イベント絵定義名) : (以下のa, b, c のいずれか) ... ,
            (
                (a)    (イベント絵画像名)
                (b)    %[
                        xoff : (座標値),
                        yoff : (座標値),
                            // デフォルトの x/ypos。
                        trans : (トランジション),
                            // このイベント絵に変更されるときのトランジション。
                    ]
                (c)    func(kag.flags, kag.sflags, env) {};
                        // (b)の辞書配列を返す関数
            )
    ],
    eventLevel : (数値),
        // イベント絵の表示レベル。省略時5。
    eventDispTrans : (トランジション),
        // イベント絵を表示/消去するときのトランジション。
    eventTrans : (トランジション),
        // イベント絵関連のトランジション
    envTrans : (トランジション),
        // 背景 or イベント絵のトランジション。

//◆位置関連
//￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣
    positions : %[
        // 位置定義。
        位置定義名 : %[
            xpos : (座標値),
            ypos : (座標値),
                // xpos, yposの値。
            time : (ms時間),
                // xpos, yposの変更にかける時間。
            disp : (KAGEnvImage.XXX),
                // 表示状態。
            level : (数値),
                // 表示レベル。
            trans : (トランジション)
                // この位置に変更するときのトランジション。
        ] ... ,
    ],
    positionTrans : (トランジション)
        // 位置変更するときのトランジション。

//◆レベル関連
//￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣
    levels : [
        // レベル定義。添字0から順に表示レベル0,1,2... のときの定義
        %[
            name : (文字列),
                // キャラクタ画像名のLEVELと置換される文字列。省略時0,1,2...。
            xoffset : (座標値),
            yoffset : (座標値),
                // キャラクタのXYオフセット。
            zoom : (数値),
                // キャラクタのカメラ用Z位置。
            emozoom : (拡大率),
                // エモーションの拡大率。省略時はzoomの値が使われる。
            trans : (トランジション),
                // この位置に変更されるときのトランジション。
            imgzoom : (拡大率),
                // 拡張立ち絵用
        ] ... ,
    ],
    defaultLevel : (数値),
        // キャラクタの表示レベルのデフォルト値。省略時0。

//◆キャラクタ関連
//￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣
    characters : %[
        // キャラクタ定義。
        (キャラクタ定義名) : %[
            initName : (文字列),
                // キャラクタ定義名差し替え。
            standName : (文字列),
                // 立ち絵名。
            nameAlias : (&TJS式 or 文字列),
                // 名前枠での表示名。
            voiceName : (文字列),
                // ボイス名。
            voiceVolume : (数値),
                // ボイス音量。
            voiceFile : (文字列),
                // ボイスファイル名の形式。
            noVoice : true,
                // 定義するとボイス未使用。    
            xoffset : (座標値),
            yoffset : (座標値),
                // キャラクタのXYオフセット。
            afx : (座標値 or "left"など文字列),
            afy : (座標値 or "top"など文字列),
                // デフォルトの回転原点。
            emoX : ([座標値 ...] or 座標値),
            emoY : ([座標値 ...] or 座標値),
                // 表示レベルごと or 一括でエモーションのXYオフセット
            emoRev : (true or false),
                // true を指定するとRevエモーション指定を使う。
            fadeValue : (ms時間),
                // デフォルトのフェード時間。
            faceLevelName : (文字列),
                // 表情枠の画像名のLEVELと置換される文字列。
            poses : %[
                // ポーズ定義。
                image : (文字列),
                    // ベース画像名。LEVEL,DRESSは置換される。
                faceImage : (文字列),
                    // 表情部分の画像名。LEVEL,DRESSは置換される。
                msgImage : (文字列),
                    // 表情枠でのベース画像名。LEVEL,DRESSは置換される。
                msgFaceImage : (文字列),
                    // 表情枠での表情部分の画像名。LEVEL,DRESSは置換される。
                afx : (座標値 or "left"など文字列),
                afy : (座標値 or "top"など文字列),
                    // デフォルトの回転原点。
                emoX : (数値),
                emoY : (数値),
                    // エモーションのXYオフセット。
                emoRev : (true of false),
                    // trueのときRevエモーション指定を使う。
                dresses : %[
                    // 服装定義。DRESSと置換される文字列。
                    (表情定義名) : (置換文字列) ... ,
                ],
                defaultDress : (文字列),
                    // デフォルトの服装。
                faces : %[
                    // 表情定義。 FACEと置換される文字列。
                    (表情定義名) : (置換文字列) ... ,
                ],
                defaultFace : (文字列),
                    // デフォルトの表情。
                levels : [
                    // 表示レベルごとの定義。添字0から順に0,1,2... のときの定義
                    %[
                        xoffset : (座標値),
                        yoffset : (座標値),
                            // キャラクタのXYオフセット。
                        zoom : (数値),
                            // カメラ用Z位置。
                        emozoom : (拡大率),
                            // エモーションの拡大率。省略時はzoomの値が使われる。
                    ] ... ,
                ],
                trans : (トランジション),
                    // このポーズに変更されるときのトランジション。
            ] ... ,
            defaultPose : (文字列),
                // デフォルトのポーズ。
            facePose : (true or false),
                // 表情ポーズを使用するか。
            noPose : (true or false),
                // trueのときポーズなし扱い。
            defaultBU : (true or false),
                 // trueのときバストアップのみ(表情枠なし)で表示。
            poseTrans : (トランジション),
                // ポーズが変更されるときのトランジション
            dressTrans : (トランジション),
                // 服装が変更されるときのトランジション。
            faceTrans : (トランジション),
                // 表情が変更されるときのトランジション。
            charTrans : (トランジション),
                // ポーズ、服装、表情が変更されるときのトランジション。
            dispTrans : (トランジション),
                // 表示/消去するときのトランジション。
            faceArea : %[ /* */ ],
            faceDiffMap : %[ /* */ ],
            faceZoom : (拡大率),
            diffTrans : (トランジション),
                // 拡張立ち絵用。
        ] ... ,
    ],
    defaultXpos : (座標値),
    defaultYpos : (座標値),
        // キャラクタのデフォルトのx/ypos。
    xoffset : (座標値),
    yoffset : (座標値),
        // キャラクタのXYオフセット。
    bothFace : (true or false),
        // trueのとき立ち絵と表情枠を同時に表示可。省略時true。
    showFaceMode : (true or false),
        // trueのときキャラクタのポーズ、服装、表情変更時に必ず表情枠再描画。
    defaultBU : (true or false),
         // trueのときキャラクタをバストアップのみ(表情枠なし)で表示。
    clearFace : (ファイル名),
        // 表情枠クリア時の画像ファイル名。
    faceApplyColor : (true or false),
        // trueのとき表情枠に時間定義による補正を適用。
    faceLevelName : (文字列),
        // 表情枠の画像名のLEVELと置換される文字列。
    dispNameFace : (true or false),
        // trueのとき名前枠の表示名、falseのときキャラ定義名でnameFacesをひく。
    nameFaces : %[
        // 表情枠の画像名マップ
        (定義名) : (画像ファイル名 or 描画関数) ... ,
    ],
    faceFadeTime : (ms時間),
        // 表情枠のフェード時間。
    charFadeValue : (ms時間),
        // キャラクタのデフォルトのフェード時間。
    poseTrans : (トランジション),
        // キャラクタのポーズが変更されるときのトランジション。
    dressTrans : (トランジション),
        // キャラクタの服装が変更されるときのトランジション。
    faceTrans : (トランジション),
        // キャラクタの表情が変更されるときのトランジション。
    charTrans : (トランジション),
        // キャラクタのポーズ、服装、表情が変更されるときのトランジション。
    charDispTrans : (トランジション),
        // キャラクタを表示/消去するときのトランジション。

//◆エモーション関連
//￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣
    emotionmap : %[
        // ポーズ別のエモーション名変換マップ。
        ([standName]_[emoPose]_[name]) : (変換後のエモーション名) ... ,
    ],
    emotions : %[
        // エモーション定義。
        (エモーション名) :%[
            name : (エモーション名),
                // エモーション名差し替え。
            image : (画像名),
                // エモーション画像。LEVELは置換される。
            xoff : (座標値),
            yoff : (座標値),
                // XY位置。
            action : (アクション),
                // このエモーションに適用するアクション。
            origin : (回転原点指定 1~9),
                // エモーションの回転原点。
            time : (ms時間),
                // アクションの時間指定。
            nowait : (true or false),
                // アクションのnowait指定。
            hide : (true or false),
                // アクションのhide指定。
            imageRev : (画像名),
                // emoRevがtrueのときのエモーション画像。LEVELは置換される。
                // emoRevはキャラクタ定義で定義。
            actionRev : (アクション),
                // emoRevがtrueのときのアクション。
            originRev : (回転原点指定1~9),
                // emoRevがtrueのときの回転原点。
        ] ... ,
    ],
    emoX : ([座標値 ...] or 座標値),
    emoY : ([座標値 ...] or 座標値),
        // 表示レベルごと or 一括でエモーションのXYオフセット。
    emoZoom : (拡大率),
        // エモーションの基準拡大率。省略時100。
    emoHideTime : (ms時間),
        // エモーションを隠すときのデフォルトの時間。

//◆環境レイヤ関連
//￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣
    layers : %[
        // 環境レイヤ定義
        (環境レイヤ定義名) : %[
            init : %[
                (コマンド名) : (属性値) ... ,
                    // 環境レイヤで実行するコマンド。登録時に実行される。
            ],
            layerDispTrans : (トランジション),
                // 表示/消去するときのトランジション。
            trans : (トランジション),
                // 画像が変更されるときのトランジション。
        ],
    ],
    layerTrans : (トランジション)，
        // 環境レイヤの画像が変更されるときのトランジション。
    layerDispTrans : (トランジション),
        // 環境レイヤを表示/消去するときのトランジション。

//◆トランジション関連
//￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣
    transitions : %[
        // トランジション定義。trans_[定義名].tjsでenvinit.tjs外に記述可。
        (トランジション定義名) : (トランジション) ... ,
            // 文字列の場合はトランジション定義名を再帰的に検索。
            // 辞書配列の場合はトランジションのコマンドを指定。
    ],
    fadeValue : (ms時間),
        // デフォルトのフェード時間。
    nosynctrans : (true or false),
        // trueのときトランジションをデフォルトで非同期実行。
    allall : (true or false),
        // all系命令においてデフォルトで全体トランジションを使うか。
    allnosync : (true or false),
        // all系命令においてデフォルトで非同期動作とするか。

//◆アクション関連
//￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣
    actions : %[
        // アクション定義。action_[定義名].tjsでenvinit.tjs外に記述可。
        (アクション定義名) : (アクション定義)
            // 文字列、配列、辞書配列などでアクションを定義。
    ],

//◆その他
//￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣
    scripts : %[
        // 画像加工スクリプト定義。script_[定義名].tjs or envscript.tjsでenvinit.tjs外に記述可。
        (スクリプト定義名) : (関数) ... ,
            // レイヤを加工する関数。
    ],
    textstyles : %[
        // テキスト書式定期。textstyle_[定義名].tjsでenvinit.tjs外に記述可。
        (書式定義名) : %[
            size : (数値),
                // 文字の大きさ。
            color : (0xRRGGBB),
                // 文字色。
            rubysize : (数値),
                // ルビサイズ。
            rubyoffset : (数値),
                // ルビオフセット。
            shadow : (true or false),
                // trueのとき影をつける。
            shadowcolor : (0xRRGGBB),
                // 影の色。
            edge : (true or false),
                // trueのとき縁取りする。
            edgecolor : (0xRRGGBB),
                // 縁取りの色。
            linespacing : (数値),
                // 行間。
            pitch : (数値),
                // 字間。
            linesize : (数値),
                // ライン高さ。
            fontface : (文字列),
                // フォント。
            bold : (true or false),
                // trueのとき太字。
        ] ... ,
    ],

//◆その他拡張立ち絵用
//￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣
    faceArea : %[/* */],
    faceZoom : (拡大率),
    searchSmallLevel : (true or false),
    diffTrans : (トランジション),
];